bart_abbreviations = {
    "12th St Oakland City Center": "12th",
    "16th St Mission": "16th",
    "19th St Oakland": "19th",
    "24th St Mission": "24th",
    "Ashby": "Ashby",
    "Balboa Park": "Balboa",
    "Bay Fair": "BayFr",
    "Castro Valley": "CstVlly",
    "Civic Center": "CivCntr",
    "Coliseum/Oakland Airport": "Cols/OAK",
    "Colma": "COLM",
    "Concord": "CONC",
    "Daly City": "DALY",
    "Downtown Berkeley": "DtwnBerk",
    "Dublin/Pleasanton": "DUBL",
    "El Cerrito del Norte": "DELN",
    "El Cerrito Plaza": "PLZA",
    "Embarcadero": "EMBR",
    "Fremont": "FRMT",
    "Fruitvale": "FTVL",
    "Glen Park": "GLEN",
    "Hayward": "HAYW",
    "Lafayette": "LAFY",
    "Lake Merritt": "LkMrrit",
    "MacArthur": "MacArthr",
    "Millbrae": "MLBR",
    "Montgomery St": "MONT",
    "North Berkeley": "NBRK",
    "North Concord/Martinez": "NCON",
    "Orinda": "ORIN",
    "Pittsburg/Bay Point": "PITT",
    "Pleasant Hill": "PHIL",
    "Powell St": "POWL",
    "Richmond": "RICH",
    "Rockridge": "ROCK",
    "San Bruno": "SBRN",
    "San Francisco Int'l Airport": "SFIA",
    "San Leandro": "SANL",
    "South Hayward": "SHAY",
    "South San Francisco": "SSAN",
    "Union City": "UCTY",
    "Walnut Creek": "WCRK",
    "West Dublin": "WDUB",
    "West Oakland": "WOAK",
    "BART Station": "BART"
}

city_abbreviations = {
    "San Francisco": "SF",
    "Oakland": "Oak",
    "Berkeley": "Berk",
    "Emeryville": "Eville",
    "North": "N",
    "South": "S",
    "East": "E",
    "West": "W"
}
